import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");

  return {
    plugins: [
      react(),
      // VitePWA generates the service worker and injects the web manifest link.
      // registerType: "autoUpdate" silently refreshes the SW when a new build deploys —
      // no "reload to update" prompt needed for a student/demo app.
      VitePWA({
        registerType: "autoUpdate",
        // devOptions disabled: running the SW in dev intercepts every HMR request
        // and causes slow reloads. The manifest is still served in dev (installability
        // prompt works). To fully test the SW, run `npm run build && npm run preview`.
        // workbox controls what the service worker pre-caches.
        workbox: {
          // Cache JS/CSS/HTML chunks generated by Vite's build.
          globPatterns: ["**/*.{js,css,html,ico,png,svg,webp,woff,woff2}"],
        },
        // The web app manifest — tells browsers/mobile this is installable.
        manifest: {
          name: "AI Friend AR",
          short_name: "AI Friend",
          description: "An AI companion with AR — powered by Gemma 4",
          start_url: "/",
          display: "standalone",     // Hides browser chrome — feels like a native app
          background_color: "#000000",
          theme_color: "#000000",
          orientation: "portrait",
          icons: [
            {
              // SVG works on modern Chrome/Android PWA installs.
              // For iOS Safari "Add to Home Screen", apple-touch-icon in index.html takes over.
              // Run `npm run generate-icons` to produce the .png versions for full coverage.
              src: "/icon-192.svg",
              sizes: "192x192",
              type: "image/svg+xml",
              purpose: "any maskable",
            },
            {
              src: "/icon-512.svg",
              sizes: "512x512",
              type: "image/svg+xml",
              purpose: "any maskable",
            },
          ],
        },
      }),
    ],
    root: ".",
    build: {
      outDir: "dist",
      target: "es2020",
    },
    server: {
      port: 5173,
      // host: true exposes the dev server on your local network IP (e.g. 192.168.x.x).
      // This is required for mobile devices on the same WiFi to reach the app.
      host: true,
      allowedHosts: env.VITE_NGROK_HOST ? [env.VITE_NGROK_HOST] : [],
      proxy: {
        "/api": {
          target: "http://localhost:8000",
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
        },
      },
    },
  };
});
